// @ts-nocheck
import * as __fd_glob_51 from "../content/docs/mobile/theming.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/mobile/team.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/mobile/push-notifications.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/mobile/profile.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/mobile/onboarding.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/mobile/index.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/mobile/in-app-updates.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/mobile/home.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/mobile/billing.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/mobile/authentication.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/web/theming.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/web/team.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/web/profile.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/web/landing-page.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/web/index.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/web/dashboard.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/web/components.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/web/billing.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/web/authentication.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/guide/shared-packages.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/guide/project-structure.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/guide/prerequisites.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/guide/installation.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/guide/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/guide/environment-variables.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/guide/billing-and-app-stores.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/deployment/web.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/deployment/mobile.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/deployment/index.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/deployment/convex.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/docs-site/index.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/backend/users.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/backend/teams.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/backend/streaming.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/backend/storage.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/backend/schema.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/backend/rag.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/backend/push-notifications.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/backend/index.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/backend/http-routes.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/backend/email.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/backend/cron-jobs.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/backend/billing.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/backend/authentication.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/backend/ai-agent.mdx?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/web/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/docs-site/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/mobile/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/guide/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/deployment/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/backend/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "backend/meta.json": __fd_glob_1, "deployment/meta.json": __fd_glob_2, "guide/meta.json": __fd_glob_3, "mobile/meta.json": __fd_glob_4, "docs-site/meta.json": __fd_glob_5, "web/meta.json": __fd_glob_6, }, {"backend/ai-agent.mdx": __fd_glob_7, "backend/authentication.mdx": __fd_glob_8, "backend/billing.mdx": __fd_glob_9, "backend/cron-jobs.mdx": __fd_glob_10, "backend/email.mdx": __fd_glob_11, "backend/http-routes.mdx": __fd_glob_12, "backend/index.mdx": __fd_glob_13, "backend/push-notifications.mdx": __fd_glob_14, "backend/rag.mdx": __fd_glob_15, "backend/schema.mdx": __fd_glob_16, "backend/storage.mdx": __fd_glob_17, "backend/streaming.mdx": __fd_glob_18, "backend/teams.mdx": __fd_glob_19, "backend/users.mdx": __fd_glob_20, "docs-site/index.mdx": __fd_glob_21, "deployment/convex.mdx": __fd_glob_22, "deployment/index.mdx": __fd_glob_23, "deployment/mobile.mdx": __fd_glob_24, "deployment/web.mdx": __fd_glob_25, "guide/billing-and-app-stores.mdx": __fd_glob_26, "guide/environment-variables.mdx": __fd_glob_27, "guide/index.mdx": __fd_glob_28, "guide/installation.mdx": __fd_glob_29, "guide/prerequisites.mdx": __fd_glob_30, "guide/project-structure.mdx": __fd_glob_31, "guide/shared-packages.mdx": __fd_glob_32, "web/authentication.mdx": __fd_glob_33, "web/billing.mdx": __fd_glob_34, "web/components.mdx": __fd_glob_35, "web/dashboard.mdx": __fd_glob_36, "web/index.mdx": __fd_glob_37, "web/landing-page.mdx": __fd_glob_38, "web/profile.mdx": __fd_glob_39, "web/team.mdx": __fd_glob_40, "web/theming.mdx": __fd_glob_41, "mobile/authentication.mdx": __fd_glob_42, "mobile/billing.mdx": __fd_glob_43, "mobile/home.mdx": __fd_glob_44, "mobile/in-app-updates.mdx": __fd_glob_45, "mobile/index.mdx": __fd_glob_46, "mobile/onboarding.mdx": __fd_glob_47, "mobile/profile.mdx": __fd_glob_48, "mobile/push-notifications.mdx": __fd_glob_49, "mobile/team.mdx": __fd_glob_50, "mobile/theming.mdx": __fd_glob_51, });